import {
  FaTableCells,
  FaChartColumn,
  FaFolderOpen,
  FaClipboard,
  FaGear,
  FaChartPie,
  FaFileLines,
  FaClock,
  FaFolderPlus,
  FaBoxArchive,
  FaListCheck,
  FaUsers,
  FaCircleCheck,
  FaShield,
  FaBell,
  FaCreditCard,
  FaFolder,
  FaFlag,
  FaBug,
  FaLock,
  FaCode,
  FaNetworkWired,
  FaBook,
  FaGlobe,
  FaCube,
  FaKey,
  FaServer,
  FaMap,
  FaDatabase,
  FaEthereum
} from "react-icons/fa6";

export const menuItems = [
  {
    title: "Dashboard",
    icon: FaTableCells,
    path: "/",
  },
  {
    title: "Projects",
    icon: FaFolder,
    path: "/projects",
    subItems: [
      { title: "All Projects", path: "/projects", icon: FaFolderOpen },
    ],
  },
  {
    title: "Writeups",
    icon: FaFlag,
    path: "/writeups",
    subItems: [
      { title: "Web3 Security", path: "/writeups/web3-security", icon: FaBug },
      { title: "Cryptography", path: "/writeups/crypto", icon: FaLock },
    ],
  },
  {
    title: "Blogs",
    icon: FaBook,
    path: "/blogs",
    subItems: [
      { title: "StakeReward Protocol", path: "/blogs/stake-reward", icon: FaCube },
      { title: "Ethernaut Fallback ", path: "/blogs/fallback-eth", icon: FaEthereum },
      { title: "Ethernaut Fal1out ", path: "/blogs/fal1out-eth", icon: FaEthereum },
      // { title: "Backend Development", path: "/blogs/backend", icon: FaServer },
      // { title: "Frontend Libraries", path: "/blogs/frontend", icon: FaCode },
      // {
      //   title: "Database Operations",
      //   path: "/blogs/database",
      //   icon: FaDatabase,
      // },
      // { title: "Web3 Development", path: "/blogs/web3", icon: FaCube },
    ],
  },
];
